services:
  messaging-hub-postgres:
    image: postgres:15.3-alpine
    container_name: messaging-hub-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postdba
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  messaging-hub-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: messaging-hub-pgadmin
    restart: always
    depends_on:
      - messaging-hub-postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=postdba
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
  messaging-hub-be-authentication:
    build: ./messaging-hub-be-authentication
    container_name: messaging-hub-be-authentication
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://messaging-hub-postgres:5432/messaginghub
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postdba
    depends_on:
      - messaging-hub-postgres
    ports:
      - 8081:8081
  messaging-hub-be-gateway:
    build: ./messaging-hub-be-gateway
    container_name: messaging-hub-be-gateway
    restart: always
    depends_on:
      - messaging-hub-be-authentication
    ports:
      - 8082:8082
  messaging-hub-be-messaging:
    build: ./messaging-hub-be-messaging
    container_name: messaging-hub-be-messaging
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://messaging-hub-postgres:5432/messaginghub
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postdba
    depends_on:
      - messaging-hub-postgres
    ports:
      - 8083:8083
  
  messaging-hub-be-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: messaging-hub-be-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  messaging-hub-be-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: messaging-hub-be-kafka
    depends_on:
      - messaging-hub-be-zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: messaging-hub-be-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://messaging-hub-be-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

networks:
  default:
    name: messaging-hub-network
    external: true