
spring:
    cloud:
        gateway:
            mvc:
                routes:
                    - id: be-authentication
                      uri: http://localhost:8081
                      predicates:
                      - Path=/messaging-hub/auth/v1/**
                    - id: be-messaging
                      uri: http://localhost:8083
                      predicates:
                      - Path=/messaging-hub/messaging/v1/**