
spring:
    cloud:
        gateway:
            mvc:
                routes:
                    - id: be-authentication
                      uri: http://messaging-hub-be-authentication:8081
                      predicates:
                      - Path=/messaging-hub/auth/v1/**